let currentCategory="love";let currentQuote="";let currentStyle="aesthetic";let audioCtx,oscillators=[],isSoundOn=false;
const CATEGORY_GROUPS={"Love & Heart":["love","friendship","happiness","sad","anger","attitude","loneliness"],"Growth":["motivation","success","confidence","dreams","self-love"],"Life":["life","wisdom","truth","karma","patience","change"],"Family":["family","relationships","breakup","trust","birthday"],"Vibe":["funny","cute","deep","short","aesthetic","dark"],"Moments":["morning","night","monday","weekend","christmas","new year","graduation"],"Soul":["spiritual","gratitude","healing"],"Media":["movie","book","anime"],"Mind":["entrepreneur","philosophy"]};
function init(){renderGroups();document.getElementById('generateBtn').onclick=generate;document.getElementById('surpriseBtn').onclick=surprise;document.getElementById('copyBtn').onclick=copyQuote;document.getElementById('saveBtn').onclick=saveImage;document.getElementById('favBtn').onclick=addFavorite;document.getElementById('soundBtn').onclick=toggleSound;document.querySelectorAll('.style-btn').forEach(b=>b.onclick=()=>setStyle(b.dataset.style));generate();loadLists();}
function renderGroups(){const container=document.getElementById('categoryGroups');container.innerHTML="";for(let group in CATEGORY_GROUPS){const title=document.createElement('div');title.className="group-title";title.textContent=group;container.appendChild(title);const chips=document.createElement('div');chips.className="chips";CATEGORY_GROUPS[group].forEach(cat=>{const chip=document.createElement('button');chip.className="chip"+(cat===currentCategory?" active":"");chip.textContent=cat;chip.onclick=()=>{currentCategory=cat;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');generate();};chips.appendChild(chip);});container.appendChild(chips);}}
function generate(){const list=QUOTES[currentCategory]||QUOTES.love;currentQuote=list[Math.floor(Math.random()*list.length)];updateCard();addToHistory(currentQuote,currentCategory);}
function surprise(){const allCats=Object.keys(QUOTES);currentCategory=allCats[Math.floor(Math.random()*allCats.length)];renderGroups();generate();}
function updateCard(){const card=document.getElementById('quoteCard');const badge=document.getElementById('categoryBadge');const text=document.getElementById('quoteText');badge.textContent=currentCategory.toUpperCase();text.textContent=currentQuote;card.className="quote-card style-"+currentStyle;card.style.background=BACKGROUNDS[currentCategory]||BACKGROUNDS.life;}
function setStyle(style){currentStyle=style;document.querySelectorAll('.style-btn').forEach(b=>b.classList.toggle('active',b.dataset.style===style));updateCard();}
function copyQuote(){navigator.clipboard.writeText(currentQuote+" - LuckyMouse Bot");const btn=document.getElementById('copyBtn');btn.textContent="Copied!";setTimeout(()=>btn.textContent="Copy",1500);}
function saveImage(){const canvas=document.getElementById('exportCanvas');const ctx=canvas.getContext('2d');const W=1080,H=1350;ctx.fillStyle="#0a0a0f";ctx.fillRect(0,0,W,H);ctx.fillStyle="white";ctx.font="700 64px serif";ctx.textAlign="center";wrapText(ctx,currentQuote,W/2,520,860,84);ctx.font="400 28px sans-serif";ctx.globalAlpha=0.7;ctx.fillText("- LuckyMouse Bot",W/2,1100);const link=document.createElement('a');link.download=`luckymouse-${currentCategory}.png`;link.href=canvas.toDataURL();link.click();}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';let lines=[];for(let n=0;n<words.length;n++){let test=line+words[n]+' ';if(ctx.measureText(test).width>maxWidth&&n>0){lines.push(line);line=words[n]+' ';}else line=test;}lines.push(line);let startY=y-(lines.length-1)*lineHeight/2;lines.forEach(l=>{ctx.fillText(l.trim(),x,startY);startY+=lineHeight;});}
function addToHistory(q,cat){let h=JSON.parse(localStorage.getItem('lm_history')||'[]');h.unshift({q,cat,time:Date.now()});h=h.slice(0,20);localStorage.setItem('lm_history',JSON.stringify(h));loadLists();}
function addFavorite(){let f=JSON.parse(localStorage.getItem('lm_fav')||'[]');if(!f.find(i=>i.q===currentQuote)){f.unshift({q:currentQuote,cat:currentCategory});localStorage.setItem('lm_fav',JSON.stringify(f));loadLists();}}
function loadLists(){const h=JSON.parse(localStorage.getItem('lm_history')||'[]');const f=JSON.parse(localStorage.getItem('lm_fav')||'[]');document.getElementById('historyList').innerHTML=h.map(i=>`<li>${i.q.slice(0,40)}...</li>`).join('');document.getElementById('favList').innerHTML=f.map(i=>`<li>${i.q.slice(0,40)}...</li>`).join('')||'<li style="opacity:0.3">No favorites yet</li>';}
function toggleSound(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();}if(isSoundOn){oscillators.forEach(o=>o.stop());oscillators=[];isSoundOn=false;document.getElementById('soundBtn').textContent="Ambient: OFF";return;}for(let freq of [110,220,330]){const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.frequency.value=freq;osc.type="sine";gain.gain.value=0.02;osc.connect(gain).connect(audioCtx.destination);osc.start();oscillators.push(osc);}isSoundOn=true;document.getElementById('soundBtn').textContent="Ambient: ON";}
init();
